### ISSUE TITLE
Hahaha Now uploads don't work in Chrome

### ISSUE THREAD

**Issue by njakobsen** [culturecode/autobiographer#65]
Can't drag and drop

**Comment by rywall** [comment]
son of a bitch!

**Comment by rywall** [comment]
fixed?

**Comment by njakobsen** [comment]
Not fixed. I upload a file. the photos controller explodes when reading the exif

Started POST "/photos" for 64.46.16.229 at Sat Dec 18 15:12:16 -0800 2010
  Processing by PhotosController#create as JS
  Parameters: {"name"=>"Screen shot 2010-11-29 at 5.23.39 PM.png", "authenticity_token"=>"tdWLoQSwHNYADB9DzpC1cVsJDfEuGSsR96SxfkKTSOc=", "file"=>#<ActionDispatch::Http::UploadedFile:0x2b88eb52d6c8 @headers="Content-Disposition: form-data; name=\"file\"; filename=\"Screen shot 2010-11-29 at 5.23.39 PM.png\"\r\nContent-Type: image/png\r\n", @content_type="image/png", @tempfile=#<File:/home/slugs/351488_0f79d19_57d0-9a1acb98-ae17-4496-9c28-7c2f88008943/mnt/tmp/RackMultipart20101218-10174-v1utbg-0>, @original_filename="Screen shot 2010-11-29 at 5.23.39 PM.png">}
Completed   in 7ms

TypeError (can't dup NilClass):
  app/controllers/photos_controller.rb:4:in `new'
  app/controllers/photos_controller.rb:4:in`create'

then I can't drag and drop any new files

**Comment by rywall** [comment]
PNG doesn't have exif. perhaps that's the issue
